version: '3'

services:
  php-web:
    build: docker-php
    ports:
      - "8080:80"
    volumes:
      - "./app:/var/www"
      - "./docker-php/php.ini:/usr/local/etc/php/php.ini"
    links:
      - mysqldb
  nodejs:
    image: node:22
    ports:
      - "3000:3000"
      - "9229:9229"
    command: bash -c "npm install && npm start"
    working_dir: "/usr/src/app"
    volumes:
      - "./app/public/assets/11/app:/usr/src/app"
      - "/usr/src/app/node_modules"
    links:
      - mysqldb
  mysqldb:
    image: mysql:8.4
    restart: always
    ports:
     - "3307:3306"
    volumes:
     - "./mysql-data:/var/lib/mysql"
     - "./mysql-sql/demo.sql:/docker-entrypoint-initdb.d/dump.sql"
    environment:
     - MYSQL_ROOT_PASSWORD=Azerty123
     - LANG=C.UTF-8
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
        - "8000:80"
    environment:
        - PMA_ARBITRARY=0
        - PMA_HOST=mysqldb
        - UPLOAD_LIMIT=50M
    restart: always
    depends_on:
        - mysqldb